"""empty message

Revision ID: 152f5821aead
Revises: b5bd9a7149df
Create Date: 2023-07-18 00:56:37.192534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '152f5821aead'
down_revision = 'b5bd9a7149df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_characters', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('character_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint('favorite_characters_unique', ['user_id', 'character_id'])

    with op.batch_alter_table('favorite_planets', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('planet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint('favorite_planets_unique', ['user_id', 'planet_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_planets', schema=None) as batch_op:
        batch_op.drop_constraint('favorite_planets_unique', type_='unique')
        batch_op.alter_column('planet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('favorite_characters', schema=None) as batch_op:
        batch_op.drop_constraint('favorite_characters_unique', type_='unique')
        batch_op.alter_column('character_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
