"""empty message

Revision ID: b395740df83b
Revises: 1d2159717f4f
Create Date: 2023-07-18 00:35:08.490096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b395740df83b'
down_revision = '1d2159717f4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_characters', schema=None) as batch_op:
        batch_op.drop_constraint('favorite_characters_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorite_characters_character_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_characters', schema=None) as batch_op:
        batch_op.create_foreign_key('favorite_characters_character_id_fkey', 'characters', ['character_id'], ['id'])
        batch_op.create_foreign_key('favorite_characters_user_id_fkey', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
